export const Users = [
    {
      id:1,
      profilePicture: "person/ritesh.jpg",
      username: "Ritesh P",
    },
    {
      id:2,
      profilePicture: "person/priti.jpg",
      username: "Priti P",
    },
    {
      id:3,
      profilePicture: "person/girish.jpg",
      username: "Girish K",
    },
    {
      id:4,
      profilePicture: "person/rushi.jpg",
      username: "Rushi C",
    },
    {
      id:5,
      profilePicture: "person/mehul.jpg",
      username: "Mehul P",
    },
    {
      id:6,
      profilePicture: "person/gaurav.jpg",
      username: "Gaurav A",
    },
    {
      id:7,
      profilePicture: "person/ashish.jpg",
      username: "Ashish P",
    },
    {
      id:8,
      profilePicture: "person/jayesh.jpg",
      username: "Jayesh P",
    },
    {
      id:9,
      profilePicture: "person/kokare.jpg",
      username: "Raj Kokare",
    },
    {
      id:10,
      profilePicture: "person/vallabh.jpg",
      username: "Vallabh N",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "post/ritesh2.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/priti.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "post/girish.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/rushi2.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/mehul.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post/gaurav.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "post/ashish.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/jayesh.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "post/kokare.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/vallabh.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];